/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model.ivms101;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * IdentityPayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IdentityPayload {
  public static final String SERIALIZED_NAME_ORIGINATOR = "originator";
  @SerializedName(SERIALIZED_NAME_ORIGINATOR)
  private Originator originator;

  public static final String SERIALIZED_NAME_BENEFICIARY = "beneficiary";
  @SerializedName(SERIALIZED_NAME_BENEFICIARY)
  private Beneficiary beneficiary;

  public static final String SERIALIZED_NAME_ORIGINATING_VASP = "originatingVASP";
  @SerializedName(SERIALIZED_NAME_ORIGINATING_VASP)
  private Person originatingVasp;

  public static final String SERIALIZED_NAME_BENEFICIARY_VASP = "beneficiaryVASP";
  @SerializedName(SERIALIZED_NAME_BENEFICIARY_VASP)
  private BeneficiaryVasp beneficiaryVasp;

  public static final String SERIALIZED_NAME_TRANSFER_PATH = "transferPath";
  @SerializedName(SERIALIZED_NAME_TRANSFER_PATH)
  private List<IntermediaryVasp> transferPath = null;

  public static final String SERIALIZED_NAME_PAYLOAD_METADATA = "payloadMetadata";
  @SerializedName(SERIALIZED_NAME_PAYLOAD_METADATA)
  private PayloadMetadata payloadMetadata;


  public IdentityPayload originator(Originator originator) {
    
    this.originator = originator;
    return this;
  }

   /**
   * Get originator
   * @return originator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Originator getOriginator() {
    return originator;
  }


  public void setOriginator(Originator originator) {
    this.originator = originator;
  }


  public IdentityPayload beneficiary(Beneficiary beneficiary) {
    
    this.beneficiary = beneficiary;
    return this;
  }

   /**
   * Get beneficiary
   * @return beneficiary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Beneficiary getBeneficiary() {
    return beneficiary;
  }


  public void setBeneficiary(Beneficiary beneficiary) {
    this.beneficiary = beneficiary;
  }


  public IdentityPayload originatingVasp(Person originatingVasp) {
    
    this.originatingVasp = originatingVasp;
    return this;
  }

   /**
   * Get originatingVasp
   * @return originatingVasp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Person getOriginatingVasp() {
    return originatingVasp;
  }


  public void setOriginatingVasp(Person originatingVasp) {
    this.originatingVasp = originatingVasp;
  }


  public IdentityPayload beneficiaryVasp(BeneficiaryVasp beneficiaryVasp) {
    
    this.beneficiaryVasp = beneficiaryVasp;
    return this;
  }

   /**
   * Get beneficiaryVasp
   * @return beneficiaryVasp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BeneficiaryVasp getBeneficiaryVasp() {
    return beneficiaryVasp;
  }


  public void setBeneficiaryVasp(BeneficiaryVasp beneficiaryVasp) {
    this.beneficiaryVasp = beneficiaryVasp;
  }


  public IdentityPayload transferPath(List<IntermediaryVasp> transferPath) {
    
    this.transferPath = transferPath;
    return this;
  }

  public IdentityPayload addTransferPathItem(IntermediaryVasp transferPathItem) {
    if (this.transferPath == null) {
      this.transferPath = new ArrayList<IntermediaryVasp>();
    }
    this.transferPath.add(transferPathItem);
    return this;
  }

   /**
   * Get transferPath
   * @return transferPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<IntermediaryVasp> getTransferPath() {
    return transferPath;
  }


  public void setTransferPath(List<IntermediaryVasp> transferPath) {
    this.transferPath = transferPath;
  }


  public IdentityPayload payloadMetadata(PayloadMetadata payloadMetadata) {
    
    this.payloadMetadata = payloadMetadata;
    return this;
  }

   /**
   * Get payloadMetadata
   * @return payloadMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PayloadMetadata getPayloadMetadata() {
    return payloadMetadata;
  }


  public void setPayloadMetadata(PayloadMetadata payloadMetadata) {
    this.payloadMetadata = payloadMetadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityPayload identityPayload = (IdentityPayload) o;
    return Objects.equals(this.originator, identityPayload.originator) &&
        Objects.equals(this.beneficiary, identityPayload.beneficiary) &&
        Objects.equals(this.originatingVasp, identityPayload.originatingVasp) &&
        Objects.equals(this.beneficiaryVasp, identityPayload.beneficiaryVasp) &&
        Objects.equals(this.transferPath, identityPayload.transferPath) &&
        Objects.equals(this.payloadMetadata, identityPayload.payloadMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originator, beneficiary, originatingVasp, beneficiaryVasp, transferPath, payloadMetadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityPayload {\n");
    sb.append("    originator: ").append(toIndentedString(originator)).append("\n");
    sb.append("    beneficiary: ").append(toIndentedString(beneficiary)).append("\n");
    sb.append("    originatingVasp: ").append(toIndentedString(originatingVasp)).append("\n");
    sb.append("    beneficiaryVasp: ").append(toIndentedString(beneficiaryVasp)).append("\n");
    sb.append("    transferPath: ").append(toIndentedString(transferPath)).append("\n");
    sb.append("    payloadMetadata: ").append(toIndentedString(payloadMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

