/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model.ivms101;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * IntermediaryVasp
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IntermediaryVasp {
  public static final String SERIALIZED_NAME_INTERMEDIARY_VASP = "intermediaryVASP";
  @SerializedName(SERIALIZED_NAME_INTERMEDIARY_VASP)
  private Person intermediaryVasp;

  public static final String SERIALIZED_NAME_SEQUENCE = "sequence";
  @SerializedName(SERIALIZED_NAME_SEQUENCE)
  private Integer sequence;


  public IntermediaryVasp intermediaryVasp(Person intermediaryVasp) {
    
    this.intermediaryVasp = intermediaryVasp;
    return this;
  }

   /**
   * Get intermediaryVasp
   * @return intermediaryVasp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Person getIntermediaryVasp() {
    return intermediaryVasp;
  }


  public void setIntermediaryVasp(Person intermediaryVasp) {
    this.intermediaryVasp = intermediaryVasp;
  }


  public IntermediaryVasp sequence(Integer sequence) {
    
    this.sequence = sequence;
    return this;
  }

   /**
   * Get sequence
   * minimum: 0
   * maximum: 9007199254740991
   * @return sequence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSequence() {
    return sequence;
  }


  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntermediaryVasp intermediaryVasp = (IntermediaryVasp) o;
    return Objects.equals(this.intermediaryVasp, intermediaryVasp.intermediaryVasp) &&
        Objects.equals(this.sequence, intermediaryVasp.sequence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intermediaryVasp, sequence);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntermediaryVasp {\n");
    sb.append("    intermediaryVasp: ").append(toIndentedString(intermediaryVasp)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

