/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AddressTypeCode
 */
@JsonAdapter(AddressTypeCode.Adapter.class)
public enum AddressTypeCode {
  
  HOME("HOME"),
  
  BIZZ("BIZZ"),
  
  GEOG("GEOG");

  private String value;

  AddressTypeCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AddressTypeCode fromValue(String value) {
    for (AddressTypeCode b : AddressTypeCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AddressTypeCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final AddressTypeCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AddressTypeCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AddressTypeCode.fromValue(value);
    }
  }
}

