/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Address
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T14:32:36.025401+02:00[Europe/Kiev]")
public class Address {
  /**
   * Gets or Sets addressType
   */
  @JsonAdapter(AddressTypeEnum.Adapter.class)
  public enum AddressTypeEnum {
    HOME("HOME"),
    
    BIZZ("BIZZ"),
    
    GEOG("GEOG");

    private String value;

    AddressTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AddressTypeEnum fromValue(String value) {
      for (AddressTypeEnum b : AddressTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AddressTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AddressTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AddressTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AddressTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ADDRESS_TYPE = "addressType";
  @SerializedName(SERIALIZED_NAME_ADDRESS_TYPE)
  private AddressTypeEnum addressType;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private String department;

  public static final String SERIALIZED_NAME_SUB_DEPARTMENT = "subDepartment";
  @SerializedName(SERIALIZED_NAME_SUB_DEPARTMENT)
  private String subDepartment;

  public static final String SERIALIZED_NAME_STREET_NAME = "streetName";
  @SerializedName(SERIALIZED_NAME_STREET_NAME)
  private String streetName;

  public static final String SERIALIZED_NAME_BUILDING_NUMBER = "buildingNumber";
  @SerializedName(SERIALIZED_NAME_BUILDING_NUMBER)
  private String buildingNumber;

  public static final String SERIALIZED_NAME_BUILDING_NAME = "buildingName";
  @SerializedName(SERIALIZED_NAME_BUILDING_NAME)
  private String buildingName;

  public static final String SERIALIZED_NAME_FLOOR = "floor";
  @SerializedName(SERIALIZED_NAME_FLOOR)
  private String floor;

  public static final String SERIALIZED_NAME_POST_BOX = "postBox";
  @SerializedName(SERIALIZED_NAME_POST_BOX)
  private String postBox;

  public static final String SERIALIZED_NAME_ROOM = "room";
  @SerializedName(SERIALIZED_NAME_ROOM)
  private String room;

  public static final String SERIALIZED_NAME_POST_CODE = "postCode";
  @SerializedName(SERIALIZED_NAME_POST_CODE)
  private String postCode;

  public static final String SERIALIZED_NAME_TOWN_NAME = "townName";
  @SerializedName(SERIALIZED_NAME_TOWN_NAME)
  private String townName;

  public static final String SERIALIZED_NAME_TOWN_LOCATION_NAME = "townLocationName";
  @SerializedName(SERIALIZED_NAME_TOWN_LOCATION_NAME)
  private String townLocationName;

  public static final String SERIALIZED_NAME_DISTRICT_NAME = "districtName";
  @SerializedName(SERIALIZED_NAME_DISTRICT_NAME)
  private String districtName;

  public static final String SERIALIZED_NAME_COUNTRY_SUB_DIVISION = "countrySubDivision";
  @SerializedName(SERIALIZED_NAME_COUNTRY_SUB_DIVISION)
  private String countrySubDivision;

  public static final String SERIALIZED_NAME_ADDRESS_LINE = "addressLine";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE)
  private List<String> addressLine = null;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;


  public Address addressType(AddressTypeEnum addressType) {
    
    this.addressType = addressType;
    return this;
  }

   /**
   * Get addressType
   * @return addressType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AddressTypeEnum getAddressType() {
    return addressType;
  }


  public void setAddressType(AddressTypeEnum addressType) {
    this.addressType = addressType;
  }


  public Address department(String department) {
    
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDepartment() {
    return department;
  }


  public void setDepartment(String department) {
    this.department = department;
  }


  public Address subDepartment(String subDepartment) {
    
    this.subDepartment = subDepartment;
    return this;
  }

   /**
   * Get subDepartment
   * @return subDepartment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubDepartment() {
    return subDepartment;
  }


  public void setSubDepartment(String subDepartment) {
    this.subDepartment = subDepartment;
  }


  public Address streetName(String streetName) {
    
    this.streetName = streetName;
    return this;
  }

   /**
   * Get streetName
   * @return streetName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStreetName() {
    return streetName;
  }


  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }


  public Address buildingNumber(String buildingNumber) {
    
    this.buildingNumber = buildingNumber;
    return this;
  }

   /**
   * Get buildingNumber
   * @return buildingNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBuildingNumber() {
    return buildingNumber;
  }


  public void setBuildingNumber(String buildingNumber) {
    this.buildingNumber = buildingNumber;
  }


  public Address buildingName(String buildingName) {
    
    this.buildingName = buildingName;
    return this;
  }

   /**
   * Get buildingName
   * @return buildingName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBuildingName() {
    return buildingName;
  }


  public void setBuildingName(String buildingName) {
    this.buildingName = buildingName;
  }


  public Address floor(String floor) {
    
    this.floor = floor;
    return this;
  }

   /**
   * Get floor
   * @return floor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFloor() {
    return floor;
  }


  public void setFloor(String floor) {
    this.floor = floor;
  }


  public Address postBox(String postBox) {
    
    this.postBox = postBox;
    return this;
  }

   /**
   * Get postBox
   * @return postBox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPostBox() {
    return postBox;
  }


  public void setPostBox(String postBox) {
    this.postBox = postBox;
  }


  public Address room(String room) {
    
    this.room = room;
    return this;
  }

   /**
   * Get room
   * @return room
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoom() {
    return room;
  }


  public void setRoom(String room) {
    this.room = room;
  }


  public Address postCode(String postCode) {
    
    this.postCode = postCode;
    return this;
  }

   /**
   * Get postCode
   * @return postCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPostCode() {
    return postCode;
  }


  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }


  public Address townName(String townName) {
    
    this.townName = townName;
    return this;
  }

   /**
   * Get townName
   * @return townName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTownName() {
    return townName;
  }


  public void setTownName(String townName) {
    this.townName = townName;
  }


  public Address townLocationName(String townLocationName) {
    
    this.townLocationName = townLocationName;
    return this;
  }

   /**
   * Get townLocationName
   * @return townLocationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTownLocationName() {
    return townLocationName;
  }


  public void setTownLocationName(String townLocationName) {
    this.townLocationName = townLocationName;
  }


  public Address districtName(String districtName) {
    
    this.districtName = districtName;
    return this;
  }

   /**
   * Get districtName
   * @return districtName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDistrictName() {
    return districtName;
  }


  public void setDistrictName(String districtName) {
    this.districtName = districtName;
  }


  public Address countrySubDivision(String countrySubDivision) {
    
    this.countrySubDivision = countrySubDivision;
    return this;
  }

   /**
   * Get countrySubDivision
   * @return countrySubDivision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountrySubDivision() {
    return countrySubDivision;
  }


  public void setCountrySubDivision(String countrySubDivision) {
    this.countrySubDivision = countrySubDivision;
  }


  public Address addressLine(List<String> addressLine) {
    
    this.addressLine = addressLine;
    return this;
  }

  public Address addAddressLineItem(String addressLineItem) {
    if (this.addressLine == null) {
      this.addressLine = new ArrayList<String>();
    }
    this.addressLine.add(addressLineItem);
    return this;
  }

   /**
   * Get addressLine
   * @return addressLine
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAddressLine() {
    return addressLine;
  }


  public void setAddressLine(List<String> addressLine) {
    this.addressLine = addressLine;
  }


  public Address country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return Objects.equals(this.addressType, address.addressType) &&
        Objects.equals(this.department, address.department) &&
        Objects.equals(this.subDepartment, address.subDepartment) &&
        Objects.equals(this.streetName, address.streetName) &&
        Objects.equals(this.buildingNumber, address.buildingNumber) &&
        Objects.equals(this.buildingName, address.buildingName) &&
        Objects.equals(this.floor, address.floor) &&
        Objects.equals(this.postBox, address.postBox) &&
        Objects.equals(this.room, address.room) &&
        Objects.equals(this.postCode, address.postCode) &&
        Objects.equals(this.townName, address.townName) &&
        Objects.equals(this.townLocationName, address.townLocationName) &&
        Objects.equals(this.districtName, address.districtName) &&
        Objects.equals(this.countrySubDivision, address.countrySubDivision) &&
        Objects.equals(this.addressLine, address.addressLine) &&
        Objects.equals(this.country, address.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressType, department, subDepartment, streetName, buildingNumber, buildingName, floor, postBox, room, postCode, townName, townLocationName, districtName, countrySubDivision, addressLine, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    subDepartment: ").append(toIndentedString(subDepartment)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    buildingNumber: ").append(toIndentedString(buildingNumber)).append("\n");
    sb.append("    buildingName: ").append(toIndentedString(buildingName)).append("\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("    postBox: ").append(toIndentedString(postBox)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    townName: ").append(toIndentedString(townName)).append("\n");
    sb.append("    townLocationName: ").append(toIndentedString(townLocationName)).append("\n");
    sb.append("    districtName: ").append(toIndentedString(districtName)).append("\n");
    sb.append("    countrySubDivision: ").append(toIndentedString(countrySubDivision)).append("\n");
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

