/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets LegalPersonNameTypeCode
 */
@JsonAdapter(LegalPersonNameTypeCode.Adapter.class)
public enum LegalPersonNameTypeCode {
  
  LEGL("LEGL"),
  
  SHRT("SHRT"),
  
  TRAD("TRAD");

  private String value;

  LegalPersonNameTypeCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LegalPersonNameTypeCode fromValue(String value) {
    for (LegalPersonNameTypeCode b : LegalPersonNameTypeCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LegalPersonNameTypeCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final LegalPersonNameTypeCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LegalPersonNameTypeCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LegalPersonNameTypeCode.fromValue(value);
    }
  }
}

