/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets NaturalPersonNameTypeCode
 */
@JsonAdapter(NaturalPersonNameTypeCode.Adapter.class)
public enum NaturalPersonNameTypeCode {
  
  ALIA("ALIA"),
  
  BIRT("BIRT"),
  
  MAID("MAID"),
  
  LEGL("LEGL"),
  
  MISC("MISC");

  private String value;

  NaturalPersonNameTypeCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static NaturalPersonNameTypeCode fromValue(String value) {
    for (NaturalPersonNameTypeCode b : NaturalPersonNameTypeCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<NaturalPersonNameTypeCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final NaturalPersonNameTypeCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public NaturalPersonNameTypeCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return NaturalPersonNameTypeCode.fromValue(value);
    }
  }
}

