/*
 * Bridge
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openvasp.core.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Originator
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-05T14:32:36.025401+02:00[Europe/Kiev]")
public class Originator {
  public static final String SERIALIZED_NAME_ORIGINATOR_PERSONS = "originatorPersons";
  @SerializedName(SERIALIZED_NAME_ORIGINATOR_PERSONS)
  private List<Person> originatorPersons = null;

  public static final String SERIALIZED_NAME_ACCOUNT_NUMBERS = "accountNumber";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NUMBERS)
  private List<String> accountNumbers = null;


  public Originator originatorPersons(List<Person> originatorPersons) {
    
    this.originatorPersons = originatorPersons;
    return this;
  }

  public Originator addOriginatorPersonsItem(Person originatorPersonsItem) {
    if (this.originatorPersons == null) {
      this.originatorPersons = new ArrayList<Person>();
    }
    this.originatorPersons.add(originatorPersonsItem);
    return this;
  }

   /**
   * Get originatorPersons
   * @return originatorPersons
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Person> getOriginatorPersons() {
    return originatorPersons;
  }


  public void setOriginatorPersons(List<Person> originatorPersons) {
    this.originatorPersons = originatorPersons;
  }


  public Originator accountNumbers(List<String> accountNumbers) {
    
    this.accountNumbers = accountNumbers;
    return this;
  }

  public Originator addAccountNumbersItem(String accountNumbersItem) {
    if (this.accountNumbers == null) {
      this.accountNumbers = new ArrayList<String>();
    }
    this.accountNumbers.add(accountNumbersItem);
    return this;
  }

   /**
   * Get accountNumbers
   * @return accountNumbers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAccountNumbers() {
    return accountNumbers;
  }


  public void setAccountNumbers(List<String> accountNumbers) {
    this.accountNumbers = accountNumbers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Originator originator = (Originator) o;
    return Objects.equals(this.originatorPersons, originator.originatorPersons) &&
        Objects.equals(this.accountNumbers, originator.accountNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originatorPersons, accountNumbers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Originator {\n");
    sb.append("    originatorPersons: ").append(toIndentedString(originatorPersons)).append("\n");
    sb.append("    accountNumbers: ").append(toIndentedString(accountNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

